package com.example.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "vehicles")
data class Vehicle(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val make: String,
    val model: String,
    val year: Int,
    val vin: String,
    val engineType: String,
    val licensePlate: String,
    val odometer: Int
) : java.io.Serializable

@Entity(tableName = "diagnostic_scans")
data class DiagnosticScan(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val vehicleId: Int,
    val timestamp: Long = System.currentTimeMillis(),
    val totalDtcCount: Int,
    val codesFound: String, // Comma separated, e.g. "P0301,P0420"
    val overview: String, // General health summary
    val odometerReading: Int
)

@Entity(tableName = "dtc_history")
data class DtcRecord(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val vehicleId: Int,
    val scanId: Int,
    val code: String, // e.g. "P0301"
    val description: String, // e.g. "Cylinder 1 Misfire Detected"
    val severity: String, // e.g. "Medium"
    val timestamp: Long = System.currentTimeMillis(),
    val likelyCauses: String, // Comma-separated causes
    val recommendations: String, // Instructions
    val fullAiAnalysis: String // Text block generated by local engine or Cloud AI
)
