package com.example.service

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import android.os.ParcelFileDescriptor
import android.print.PageRange
import android.print.PrintAttributes
import android.print.PrintDocumentAdapter
import android.print.PrintDocumentInfo
import android.print.PrintManager
import android.util.Base64
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.core.content.FileProvider
import com.example.R
import com.example.data.DiagnosticScan
import com.example.data.DtcRecord
import com.example.data.Vehicle
import java.io.ByteArrayOutputStream
import java.io.File
import java.text.SimpleDateFormat
import java.util.*

class PdfExportService(private val context: Context) {

    fun exportRepairManifesto(
        vehicle: Vehicle,
        scan: DiagnosticScan,
        records: List<DtcRecord>
    ) {
        val webView = WebView(context)
        val htmlContent = generateHtml(vehicle, scan, records)

        webView.webViewClient = object : WebViewClient() {
            override fun onPageFinished(view: WebView?, url: String?) {
                val printManager = context.getSystemService(Context.PRINT_SERVICE) as PrintManager
                val jobName = "Mekanik_AI_Report_${vehicle.licensePlate}_${scan.id}"
                val printAdapter = webView.createPrintDocumentAdapter(jobName)
                
                printManager.print(
                    jobName,
                    printAdapter,
                    PrintAttributes.Builder().build()
                )
            }
        }

        webView.loadDataWithBaseURL(null, htmlContent, "text/html", "utf-8", null)
    }

    fun shareRepairManifesto(
        vehicle: Vehicle,
        scan: DiagnosticScan,
        records: List<DtcRecord>
    ) {
        val webView = WebView(context)
        val htmlContent = generateHtml(vehicle, scan, records)

        webView.webViewClient = object : WebViewClient() {
            override fun onPageFinished(view: WebView?, url: String?) {
                val jobName = "Mekanik_AI_Share_${vehicle.licensePlate}_${scan.id}"
                val printAdapter = webView.createPrintDocumentAdapter(jobName)
                
                val attributes = PrintAttributes.Builder()
                    .setMediaSize(PrintAttributes.MediaSize.ISO_A4)
                    .setResolution(PrintAttributes.Resolution("pdf", "pdf", 600, 600))
                    .setMinMargins(PrintAttributes.Margins.NO_MARGINS)
                    .build()

                val file = File(context.cacheDir, "$jobName.pdf")
                val pfd = ParcelFileDescriptor.open(file, ParcelFileDescriptor.MODE_READ_WRITE or ParcelFileDescriptor.MODE_CREATE or ParcelFileDescriptor.MODE_TRUNCATE)

                printAdapter.onLayout(null, attributes, null, object : PrintDocumentAdapter.LayoutResultCallback() {
                    override fun onLayoutFinished(info: PrintDocumentInfo?, changed: Boolean) {
                        printAdapter.onWrite(arrayOf(PageRange.ALL_PAGES), pfd, null, object : PrintDocumentAdapter.WriteResultCallback() {
                            override fun onWriteFinished(pages: Array<out PageRange>?) {
                                pfd.close()
                                sharePdfFile(file, vehicle)
                            }
                        })
                    }
                }, null)
            }
        }

        webView.loadDataWithBaseURL(null, htmlContent, "text/html", "utf-8", null)
    }

    private fun sharePdfFile(file: File, vehicle: Vehicle) {
        val uri: Uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, "Mekanik AI Repair Manifesto: ${vehicle.year} ${vehicle.make} ${vehicle.model}")
            putExtra(Intent.EXTRA_TEXT, "Attached is the diagnostic Repair Manifesto for the vehicle ${vehicle.licensePlate} generated by Mekanik AI.")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }

        context.startActivity(Intent.createChooser(intent, "Share Repair Manifesto").apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        })
    }

    private fun generateHtml(
        vehicle: Vehicle,
        scan: DiagnosticScan,
        records: List<DtcRecord>
    ): String {
        val logoBase64 = getLogoBase64()
        val dateFormat = SimpleDateFormat("MMMM dd, yyyy HH:mm", Locale.getDefault())
        val dateStr = dateFormat.format(Date(scan.timestamp))
        val neuralId = "NEURAL-ID-${scan.id}-${scan.timestamp.toString().takeLast(4)}"

        val dtcRows = if (records.isEmpty()) {
            "<tr><td colspan='4' style='text-align:center; padding: 20px; color: #666;'>No fault codes detected. System reporting nominal health.</td></tr>"
        } else {
            records.joinToString("") { record ->
                """
                <tr>
                    <td class="code">${record.code}</td>
                    <td>
                        <div class="desc">${record.description}</div>
                        <div class="status-tag ${record.status.lowercase()}">${record.status.uppercase()}</div>
                    </td>
                    <td class="severity ${record.severity.lowercase()}">${record.severity.uppercase()}</td>
                    <td class="recommendation">${record.recommendations.split("|").firstOrNull() ?: "See full report"}</td>
                </tr>
                """
            }
        }

        return """
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                @page { margin: 0.5in; }
                body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; line-height: 1.6; margin: 0; padding: 0; background: #fff; }
                .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 3px solid #00E676; padding-bottom: 20px; margin-bottom: 30px; }
                .logo { height: 60px; }
                .report-title { text-align: right; }
                .report-title h1 { margin: 0; color: #1B5E20; font-size: 24px; letter-spacing: 1px; }
                .report-title p { margin: 5px 0 0; color: #666; font-size: 12px; font-weight: bold; }
                
                .section { margin-bottom: 30px; }
                .section-title { background: #f5f5f5; padding: 8px 15px; font-weight: bold; border-left: 4px solid #00E676; margin-bottom: 15px; font-size: 14px; text-transform: uppercase; }
                
                .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
                .info-item { margin-bottom: 10px; }
                .info-label { font-size: 11px; color: #888; text-transform: uppercase; font-weight: bold; }
                .info-value { font-size: 14px; font-weight: 600; color: #222; }
                
                .neural-summary { background: #E8F5E9; border-radius: 8px; padding: 20px; border: 1px solid #C8E6C9; }
                .neural-summary p { margin: 0; font-style: italic; color: #2E7D32; font-size: 14px; }
                
                table { width: 100%; border-collapse: collapse; margin-top: 10px; }
                th { background: #333; color: #fff; text-align: left; padding: 12px 15px; font-size: 12px; text-transform: uppercase; }
                td { padding: 12px 15px; border-bottom: 1px solid #eee; vertical-align: top; font-size: 13px; }
                
                .code { font-family: monospace; font-weight: bold; color: #00E676; background: #f0f0f0; border-radius: 4px; padding: 4px 8px; font-size: 14px; }
                .severity { font-weight: bold; }
                .severity.critical { color: #D32F2F; }
                .severity.high { color: #E64A19; }
                .severity.medium { color: #F57C00; }
                .severity.low { color: #388E3C; }
                
                .status-tag { display: inline-block; font-size: 9px; font-weight: bold; padding: 2px 6px; border-radius: 4px; margin-top: 5px; }
                .status-tag.pending { background: #FFF9C4; color: #F57F17; }
                .status-tag.permanent { background: #FFCDD2; color: #B71C1C; }
                .status-tag.stored { background: #E0E0E0; color: #424242; }
                
                .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #eee; display: flex; justify-content: space-between; font-size: 10px; color: #999; }
                .auth-badge { border: 1px solid #00E676; padding: 5px 10px; border-radius: 4px; color: #1B5E20; font-weight: bold; }
            </style>
        </head>
        <body>
            <div class="header">
                <img src="data:image/png;base64,$logoBase64" class="logo" />
                <div class="report-title">
                    <h1>REPAIR MANIFESTO</h1>
                    <p>OFFICIAL VEHICLE HEALTH CERTIFICATE</p>
                </div>
            </div>

            <div class="section">
                <div class="section-title">Vehicle Identification</div>
                <div class="grid">
                    <div>
                        <div class="info-item">
                            <div class="info-label">Vehicle Name</div>
                            <div class="info-value">${vehicle.year} ${vehicle.make} ${vehicle.model}</div>
                        </div>
                        <div class="info-item">
                            <div class="info-label">License Plate</div>
                            <div class="info-value">${vehicle.licensePlate}</div>
                        </div>
                    </div>
                    <div>
                        <div class="info-item">
                            <div class="info-label">VIN Identifier</div>
                            <div class="info-value">${vehicle.vin}</div>
                        </div>
                        <div class="info-item">
                            <div class="info-label">Odometer at Scan</div>
                            <div class="info-value">${scan.odometerReading} km</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="section">
                <div class="section-title">Neural Diagnostic Summary</div>
                <div class="neural-summary">
                    <p>${scan.overview}</p>
                </div>
            </div>

            <div class="section">
                <div class="section-title">ECU Fault Code Analysis</div>
                <table>
                    <thead>
                        <tr>
                            <th width="15%">Code</th>
                            <th width="40%">Description & Status</th>
                            <th width="15%">Severity</th>
                            <th width="30%">Primary Recommendation</th>
                        </tr>
                    </thead>
                    <tbody>
                        $dtcRows
                    </tbody>
                </table>
            </div>

            <div class="footer">
                <div>
                    <div>Generated on: $dateStr</div>
                    <div>Mekanik AI Mobile Diagnostics v1.0.1</div>
                </div>
                <div class="auth-badge">
                    SECURE NEURAL SCAN ID: $neuralId
                </div>
            </div>
        </body>
        </html>
        """.trimIndent()
    }

    private fun getLogoBase64(): String {
        return try {
            val bitmap = BitmapFactory.decodeResource(context.resources, R.drawable.mekanik_brand_logo_original_1780274248851)
            val outputStream = ByteArrayOutputStream()
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, outputStream)
            Base64.encodeToString(outputStream.toByteArray(), Base64.NO_WRAP)
        } catch (e: Exception) {
            ""
        }
    }
}
